### ISSUE TITLE
Update All Button

### ISSUE THREAD

**Issue by trevorgerhardt** [conveyal/gtfs-data-manager#57] opened 2014-12-17 19:27 UTC
When creating a new deployment with mostly feeds from outsider sources it would be nice to have an "Update All" button. Or maybe just an "Update" button in the table view of all the feeds.

**Comment by mattwigway** [comment] 2015-01-29 14:46
This is implemented on the back end; you can hit /fetchGtfs while logged in. It's currently a GET request, which isn't the right way to do this.

**Comment by mattwigway** [comment] 2015-01-29 17:53
Also, duplicate of #11.

**Closed by mattwigway** 2015-01-29 17:53 UTC
Labels: enhancement
